### PR TITLE
Make redhat_packages and virt use json_query instead of Python item a…

### LINKED ISSUE #502: Ansible stops on errors in the playbook
Ansible can recover from errors in task execution, but if there are errors in the playbook itself, it stops.

Steps to reproduce:
  1. Set up an environment where ssh will fail. Get Sonar to start an inspect scan anyway (you'll need to bypass the connect scan first)
  2. Get failure in `redhat_packages` role. It can't get the `['stdout_lines']` of a task that failed.

I can fix any individual instance of this, but the overall pattern is a hit to reliability. We need to think about this.

### PR DESCRIPTION
**Pull request by noahl**
…ccess

This lets the playbook continue when tasks fail.

Closes #502 .

### CODE REVIEW

**Comment by chambridge** [comment]
Have you run this change across a large set of systems? Can you provide result output?

Other sections of the code we have done something like:
```
- name: set internal_release_file when a release file is found
  set_fact: internal_release_file={{ internal_release_found["stdout_lines"][0] }}
  when:
    - '"stdout_lines" in internal_release_found'
    - 'internal_release_found["stdout_lines"]|length > 0'
    - 'internal_release_found["stdout_lines"][0]|length > 0'
```

Just trying to understand the pros/cons of this update.

**Comment by noahl** [comment]
I've run it on three machines so far. I think I have good coverage of the `redhat_packages` changes, but I'm not sure how to test the changes in `virt` yet. Anyway, here's some output:
```
sonar-none-rhel-7-vc:
 'redhat_packages_gpg_is_redhat': True
 'redhat_packages_gpg_num_rh_packages': '339',
 'redhat_packages_all_count': {'rc': 0, 'stdout': '339\r\n', 'stdout_lines': ['339'], 'stderr': 'Shared connection to 10.10.181.199 closed.\r\n', 'changed': True, '_ansible_no_log': False},
 'redhat_packages_gpg_num_installed_packages': '339',
 'redhat_packages_gpg_last_installed': 'firewalld-0.4.4.4 Installed:Tue 09 Jan 2018 03:14:50 PM EST',
 'redhat_packages_gpg_last_built': 'selinux-policy-targeted-3.13.1 Built:Mon 10 Jul 2017 12:02:54 PM EDT',
 'redhat_packages_certs_cmd': {'rc': 1, 'stdout': '', 'stdout_lines': [], 'stderr': 'Shared connection to 10.10.181.199 closed.\r\n', 'changed': True, '_ansible_no_log': False, 'failed': True},
 'redhat_packages_certs': '',
 'virt_virt': 'virt-guest',
 'virt_type': 'vmware',
 'virt_num_guests': '',
 'virt_num_running_guests': ''

sonar-none-fedora-26-vc:
 'redhat_packages_gpg_is_redhat': False,
 'redhat_packages_gpg_num_rh_packages': '0',
 'redhat_packages_all_count': {'rc': 0, 'stdout': '381\r\n', 'stdout_lines': ['381'], 'stderr': 'Shared connection to 10.10.182.46 closed.\r\n', 'changed': True, '_ansible_no_log': False},
 'redhat_packages_gpg_num_installed_packages': '381',
 'redhat_packages_certs_cmd': {'rc': 1, 'stdout': '', 'stdout_lines': [], 'stderr': 'Shared connection to 10.10.182.46 closed.\r\n', 'changed': True, '_ansible_no_log': False, 'failed': True},
 'redhat_packages_certs': '',
 'virt_virt': 'N/A (dmidecode not found)',
 'virt_type': 'N/A (dmidecode not found)',
 'virt_num_guests': '',
 'virt_num_running_guests': ''

sonar-none-centos-7-vc:
 'redhat_packages_gpg_is_redhat': False,
 'redhat_packages_gpg_num_rh_packages': '0',
 'redhat_packages_all_count': {'rc': 0, 'stdout': '381\r\n', 'stdout_lines': ['381'], 'stderr': 'Shared connection to 10.10.182.46 closed.\r\n', 'changed': True, '_ansible_no_log': False},
 'redhat_packages_gpg_num_installed_packages': '381',
 'redhat_packages_certs_cmd': {'rc': 1, 'stdout': '', 'stdout_lines': [], 'stderr': 'Shared connection to 10.10.182.46 closed.\r\n', 'changed': True, '_ansible_no_log': False, 'failed': True},
 'redhat_packages_certs': '',
 'virt_virt': 'N/A (dmidecode not found)',
 'virt_type': 'N/A (dmidecode not found)',
 'virt_num_guests': '',
 'virt_num_running_guests': ''
```

To your point about other parts of the code using when clauses, I could certainly do that. One advantage of `json_query` is that it will always have some sort of result, even if it's null. I like that because in the `redhat_packages` role, other tasks have when clauses that depend on the output of the json_query. If it didn't have some kind of result, I would have to make those when clauses more complicated.

(I know we could also accomplish this by having two `set_fact` tasks, one with the when clauses you put in your comment and another if those are not true, but that seems a lot more complicated to me.)

**Comment by noahl** [comment]
Actually, I think the examples above tested about half of the virt code. I don't have any information on what this does on a virt host, but as far as I know I don't really have access to a test machine for that.

**Comment by chambridge** [comment]
Based on your output it looks like we had some unnecessary facts being collected. Should fix
`redhat_packages_certs_cmd` --> `internal_redhat_packages_certs_cmd`
`redhat_packages_all_count`  --> `internal_redhat_packages_all_count`

I think your explanation is fine I just wonder whether it is worth documenting potential results of `json_query` in the task comments for future maintenance.

**Comment by noahl** [comment]
@chambridge I added `internal_` to the facts you mentioned and added a comment about why I used json_query and what the output will be. Please take a look!

**Pull request merged**
