### PR TITLE
build: upgrade to python 3.12

### PR DESCRIPTION
**Pull request by bruno-fs**
Assortment of upgrades:
- upgrade python to version 3.12
- get rid of python 3.11
- upgrade pybuild-deps, effectively fixing the issue preventing us to update pip
- hold back celery version to <5.4 due to a regression

### CODE REVIEW

**Comment by bruno-fs** [comment]
The changes on `requirements*.txt` were tested in private downstream builds.

**Comment by ruda** [comment]
Don't forget to set `3.12` in https://github.com/quipucords/quipucords/blob/main/setup.py.
Can we drop `setup.py`?

**Review by ruda — APPROVED** [review]
LGTM, just take a look at `setup.py`.

**Review by infinitewarp — APPROVED** [review]

**Review by infinitewarp — CHANGES_REQUESTED** [review]
https://github.com/quipucords/quipucords/pull/2723#issuecomment-2291673865

Blocking so we don't forget to look at this. ☝️

**Review by infinitewarp — APPROVED** [review]

**Pull request merged**
