### PR TITLE
Add status message to ScanJob and ScanTask

### LINKED ISSUE #467: Capture error message in scan task and scan job for failed scan
## Specify type:
- Enhancement

## Description:
Currently scan jobs and scan tasks only contain a status that could result in a failure. Some minimal information should be passed to the user on a failure to help them resolve the issue, even if the minimal message is to review the server logs due to an unknown exception.

### PR DESCRIPTION
**Pull request by kholdaway**
Closes #467

### CODE REVIEW

**Comment by kholdaway** [comment]
Are you referring to just the scantask/job or all the error messages from satellite/vcenter/network connect and inspect?  I can externalize these at part of the PR, but most of the messages in this PR were moved from logger.error to a message variable.  I figured we could tackle that as part of the logging cleanup.

**Comment by chambridge** [comment]
I’m just referring to the job/task messages that we expect to present to users via the api or cli.

**Comment by kholdaway** [comment]
I externalized the status messages for ScanJob and ScanTask.

**Comment by kholdaway** [comment]
https://github.com/quipucords/quipucords/issues/528

**Pull request merged**
