### PR TITLE
Handle Satellite errors on a per system basis. (Beta fix)

### PR DESCRIPTION
**Pull request by chambridge**

### CODE REVIEW

**Comment by chambridge** [comment]
@mdvickst If you are able to pull this branch and verify that would be ideal, as I can only verify with mocked unit tests.

**Comment by mdvickst** [comment]
I think the fix worked, I now show the scan as completed with 1 "systems_failed" under the Satellite inspect scan. 

qpc telling me that there is no report summary available for the scan though, is that expected?

[root@mvickstr-rhel7 quipucords-beta]# qpc scan show --id 1
{
    "end_time": "2018-02-08T08:43:17.943573",
    "fact_collection_id": 1,
    "id": 1,
    "options": {
        "max_concurrency": 50
    },
    "scan_type": "inspect",
    "sources": [
        {
            "id": 1,
            "name": "local_vms",
            "source_type": "network"
        },
        {
            "id": 2,
            "name": "sat6-sa-lab",
            "source_type": "satellite"
        }
    ],
    "start_time": "2018-02-08T08:36:45.717464",
    "status": "completed",
    "status_message": "Job is complete.",
    "systems_count": 182,
    "systems_failed": 1,
    "systems_scanned": 181,
    "tasks": [
        {
            "end_time": "2018-02-08T08:37:08.086823",
            "scan_type": "connect",
            "source": 1,
            "start_time": "2018-02-08T08:36:45.734731",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 256,
            "systems_failed": 252,
            "systems_scanned": 4
        },
        {
            "end_time": "2018-02-08T08:37:10.042337",
            "scan_type": "connect",
            "source": 2,
            "start_time": "2018-02-08T08:37:08.090679",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 178,
            "systems_failed": 0,
            "systems_scanned": 178
        },
        {
            "end_time": "2018-02-08T08:37:45.968676",
            "scan_type": "inspect",
            "source": 1,
            "start_time": "2018-02-08T08:37:10.045848",
            "status": "completed",
            "status_message": "success",
            "systems_count": 4,
            "systems_failed": 0,
            "systems_scanned": 4
        },
        {
            "end_time": "2018-02-08T08:43:16.394512",
            "scan_type": "inspect",
            "source": 2,
            "start_time": "2018-02-08T08:37:45.974022",
            "status": "completed",
            "status_message": "Task is complete.",
            "systems_count": 178,
            "systems_failed": 1,
            "systems_scanned": 177
        }
    ]
}
[root@mvickstr-rhel7 quipucords-beta]#  qpc report summary --id 1 --csv --output-file=test.csv
No report summary available for scan job 1.

**Comment by chambridge** [comment]
No, if it created a fact collection ID I would expect a summary report.  Can you share the logs? I want to see if something went wrong with the fingerprint engine or report generation.

**Comment by chambridge** [comment]
Also try doing a qpc login and trying again. We fixed a bug with token handling that may need to be backported to beta.

**Comment by mdvickst** [comment]
[sonar_logs_mvickstr-2-22-18.tar.gz](https://github.com/quipucords/quipucords/files/1748269/sonar_logs_mvickstr-2-22-18.tar.gz)

**Comment by mdvickst** [comment]
Was the suggestion to login and then run the scan again or login and try to view the report again? I tried the second one and got the same results.

**Comment by chambridge** [comment]
I was the second. Try login and then the qpc report command. 

I don't see anything in the logs.
```
INFO 2018-02-08 08:43:16,559 __init__ 28 140671101929216 Fingerprint engine (FC=1) - start processing
INFO 2018-02-08 08:43:17,930 __init__ 28 140671101929216 Fingerprint engine (FC=1) - end processing (valid fingerprints=181, invalid fingerprints=0)
```

Can you use your browser and try the `/api/v1/reports/?fact_collection_id=1` endpoint to see if there is anything is there? Or `/api/v1/reports/` to see all the summary reports?

**Comment by mdvickst** [comment]
Yes the data is in the api/v1/reports. I've tried to save that output to the attached archive. 
[Archive 2.zip](https://github.com/quipucords/quipucords/files/1748624/Archive.2.zip)

**Comment by chambridge** [comment]
any logs in `~/.local/share/qpc`?

Also if you open the browser and select the **GET**, there is an arrow with a `csv` option. Can you try that and see if the server shows any errors?

**Comment by mdvickst** [comment]
[qpc.log.zip](https://github.com/quipucords/quipucords/files/1748857/qpc.log.zip)

[download.csv.zip](https://github.com/quipucords/quipucords/files/1748865/download.csv.zip)

**Comment by chambridge** [comment]
Tried to reproduce with the info you gave me on my server, but no luck:
```
$ qpc scan start --sources sat6
Scan "1" started.
$ qpc report summary --id 1 --csv --output-file=test.csv

Report written successfully..
```
We'll have to try against your server when you get a chance.

**Pull request merged**
