### PR TITLE
Jboss string update

### PR DESCRIPTION
**Pull request by justinkreft**
Adding strings to the fingerprinter to identify newer versions of JBoss EAP and JWS.

### CODE REVIEW

**Comment by justinkreft** [comment]
Where are we on this. it has been 26 days.

**Comment by kholdaway** [comment]
@justinkreft How have you tested this? 
@himmAllRight How do you feel about this?

From a code perspective, it looks fine to me if we think it has been tested.

**Review by kholdaway — APPROVED** [review]
Approved.  Can merge once SEAP/QE feel comfortable with testing.

**Comment by justinkreft** [comment]
I've tested this on several systems and it is an improvement for the latest Jboss EAP and JWS. I think it can be merged

**Comment by kholdaway** [comment]
@justinkreft We let the submitter of the PR merge when approved.

**Comment by justinkreft** [comment]
oh I didn't know. merging now then

**Comment by kholdaway** [comment]
@justinkreft We also usually click the delete branch button after it's merged. I did that for this PR.

**Pull request merged**
